version: '2'



services:
RUN --mount=type=secret,id=secrets source /run/secrets/my_env \ 
 web:
    image: nicopaez/jobvacancy-ruby:1.3.0
    links:
      - db
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      RACK_ENV: "production"
      DATABASE_URL: "postgres://postgres:Passw0rd!@db:5432/postgres"
    depends_on:
      - db
  db:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_PASSWORD: ${POSGRES_PASS}