kind: ConfigMap 
apiVersion: v1 
metadata:
  name: example-configmap 
data:
  # Configuration values can be set as key-value properties
CONFIG_LOCATION=/mydata/config.json
SECRETS_LOCATION=/mysecrets/secret.json