apiVersion: apps/v1

kind: Deployment

metadata:

  name: telegram-deployment

  labels:

    app: telegram

spec:

  replicas: 0

  selector:

    matchLabels:

      app: telegram

  template:

    metadata:

      labels:

        app: telegram

    spec:

      containers:

      - name: telegram

        image: nicopaez/telegrambot:0.0.7

	arguments: -e TELEGRAM_TOKEN=COMPLETAR
